name: Build and deploy React (Vite) frontend to Azure Web App - frontend-m

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # 3️⃣ Install dependencies and build
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # 4️⃣ Upload build artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      # 1️⃣ Download build artifact
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build

      # 2️⃣ Login to Azure using Service Principal JSON
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3️⃣ Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'frontend-m'    # 👈 your Web App name
          slot-name: 'Production'
          package: .
